.travis.yml
README.md
composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Add a Travis CI build for [plugin-vscode ](https://github.com/ballerina-platform/plugin-vscode) repository, and update the plugin version to Swan Lake Preview5.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Add a Travis CI build

---

README.md

Update Travis CI build repo to the private build.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Update Travis build repo

---

.travis.yml
.vscode/launch.json
package.json
test/core/ballerina-extention.test.ts
test/data/hello_world.bal
test/debugger/debugger.test.ts
tsconfig.json

Enable vscode plugin tests.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Enable plugin tests

---

package.json
src/core/extension.ts
src/extension.ts
src/overview/activator.ts
src/overview/renderer.ts
src/project-tree-view/activator.ts
src/project-tree-view/project-overview.ts
src/project-tree-view/project-tree.ts

Enable 'Ballerina Project Overview' and goto service/function definition upon the click event.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/17

Enable Ballerina Project Overview

---

package.json
src/project/activator.ts
src/project/cli-cmds/cmd-runner.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts
src/project/cli-cmds/utils.ts
src/telemetry/components.ts
src/telemetry/events.ts

Add ballerina run command and refactor ballerina test run.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/15

Add ballerina run command

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Preview5-SNAPSHOT to 2.0.0-Preview5.

Update release version to 2.0.0-Preview5

---

.github/workflows/publish-extension.yml

Add git action to publish the ballerina vscode extension to the marketplace.
Related to https://github.com/ballerina-platform/plugin-vscode/issues/5

Add git action to publish the extension

---

.github/workflows/draft-release-on-docker-build.yml
.github/workflows/draft-release.yml
.github/workflows/resources/Dockerfile
.github/workflows/test-pr.yml
.vscodeignore
build.gradle

Add git actions that attach the built VSIX file to a release draft.
Related to: https://github.com/ballerina-platform/plugin-vscode/issues/5

Add git actions

---

src/overview/activator.ts

Correct file focus position selection of project overview according to the new ballerina distribution.
Fixes https://github.com/ballerina-platform/plugin-vscode/issues/24

Correct file position selection

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Preview5 to 2.0.0-Preview6-SNAPSHOT.

Update version to 2.0.0-Preview6-SNAPSHOT

---

.vscodeignore

Remove unused files packed in plugin vsix.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/26

Remove unused files from vsix

---

.gitignore
.vscodeignore
composer/build.gradle
composer/configs/common.tsconfig.json
composer/package-lock.json
composer/package.json
package.json
settings.gradle
src/core/extended-language-client.ts
src/debugger/config-provider.ts
src/server/server.ts
src/trace-logs/traces.ts
src/utils/webview-utils.ts
tsconfig.json

Pack composer-library files inside extensionPath/resources/jslibs directory.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/28

Pack composer libraries inside the extension

---

package.json
src/project/cli-cmds/build.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts

Is included with the following fixes.
- Dynamically change the user options for extension commands depending on the current editor file
- Multi-level command options for 'Build' command
Fix https://github.com/ballerina-platform/plugin-vscode/issues/30

Dynamically change user options for current file

---

build.gradle
composer/build.gradle
settings.gradle

Fix the issue with packing webview templates.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Fix extension build

---

composer/packages/bbe/src/ExampleList.tsx

Fix https://github.com/ballerina-platform/plugin-vscode/issues/10

Add warn message on examples non availability.

---

src/project/cli-cmds/run.ts

Add choreo observability for the ballerina run command execution of the current file.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/32

Add choreo observability for current file

---

package.json
src/docs/activator.ts
src/extension.ts
src/project-tree-view/activator.ts

Diable as they are not working with new API changes.

Disable project overview and doc preview

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Preview6-SNAPSHOT to 2.0.0-Preview7-SNAPSHOT.

Update version to 2.0.0-Preview7-SNAPSHOT

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Preview-SNAPSHOT to 2.0.0-Preview7.

Update version to 2.0.0-Preview7

---

composer/packages/lang-service/src/client/client.ts
package.json
src/core/extended-language-client.ts
src/project-tree-view/activator.ts
src/project-tree-view/project-overview.ts
src/utils/rpc/handler.ts

Enable project overview with new Project APIs.
Related issue: https://github.com/ballerina-platform/plugin-vscode/issues/99

Enable project overview

---

src/core/extended-language-client.ts
src/project/activator.ts
src/project/cli-cmds/build.ts
src/project/cli-cmds/doc.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts

Update plugin commands to compatible with new CLI commands.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/110
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/27555

Update plugin commands

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Preview8-SNAPSHOT to 2.0.0-Preview8.

Update version to 2.0.0-Preview8

---

composer/packages/ast-model/src/source-gen/tests/index.test.ts
composer/packages/lang-service/src/client/ast-models.ts
composer/packages/lang-service/src/client/client.ts
composer/packages/lang-service/src/client/model.ts
composer/packages/lang-service/src/client/test-utils.ts
resources/templates/http-service.bal
resources/utils/messaging.js
src/core/extended-language-client.ts
src/utils/rpc/handler.ts
test/language-server/lang-client.test.ts

Remove fragment service, ast and astDidChange API usages, and update with syntaxTree API.
Related issue https://github.com/ballerina-platform/plugin-vscode/issues/105

Update LS changes

---

src/core/extended-language-client.ts
test/debugger/debugger.test.ts
test/language-server/lang-client.test.ts

Add test cases for getPackages, getBallerinaProject, fetchExamples, and foldingRange APIs.

Add language client test cases

---

test/data/hello_world.bal
test/language-server/lang-client.test.ts

Add test cases for textDocument/hover, textDocument/definition, and textDocument/codeAction language client requests.

Add hover, goto def, and code action tests

---

src/core/extended-language-client.ts
src/project/activator.ts
src/project/cli-cmds/build.ts
src/project/cli-cmds/cmd-runner.ts
src/project/cli-cmds/doc.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts
test/language-server/lang-client.test.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/139

Fix incorrect package check for single file projects

---

composer/packages/lang-service/src/server/utils.ts
src/core/extended-language-client.ts
src/core/extension.ts
src/debugger/config-provider.ts
src/project/cli-cmds/cmd-runner.ts
src/utils/rpc/handler.ts
test/debugger/debugger.test.ts
test/language-server/lang-client.test.ts
test/test-util.ts

Update with the following SLP9 changes
- Ballerina CLI command change
- 'ballerinaProject/packages' LS API removal
- Doc generation code action/lens changes

Update with SLP9 changes

---

package.json
src/core/extension.ts
src/project/activator.ts

Disable notification that comes upon opening a file inside a ballerina project.
Due to [this](https://github.com/ballerina-platform/ballerina-lang/pull/28053) mentioned issue.

Disable notification upon file open

---

package.json
src/core/extension.ts

This reverts commit 1e933cca48b0991e58036b5b378214143781141f as per https://github.com/ballerina-platform/ballerina-lang/issues/28056#issuecomment-764549141

Revert "Disable toml support"

---

src/project/cli-cmds/k8s.ts

Change base image of k8s.toml generation

---

src/core/extension.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/53

Skip version mismatch error for SL

---

src/core/extension.ts

Fix 'Cannot read property 'map' of null' error at plugin initialization.

Fix error at plugin initialization

---

src/core/extension.ts

Add isNewCLICmdSupported true for swan lake releases.

Add new cli support missing config

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-Alpha-SNAPSHOT to 2.0.0-alpha.

Update version to 2.0.0-alpha

---

src/project/cli-cmds/k8s.ts
src/utils/project-utils.ts

$Subject
Allows users to create Kubernetes.toml even when they have opened non bal files such as Ballerina.toml in the project directory. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …

Avoid bal check for k8s creation

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-alpha to 2.0.0-beta-SNAPSHOT.

Update version to 2.0.0-beta-SNAPSHOT

---

src/core/extension.ts
src/utils/logger.ts

> Many beginning Ballerina users troubles with getting VSCode running with the correct Ballerina SDK version. Even for the pro-users there might be occasions that accidentally they setup wrong Ballerina SDK version. This status bar item shows the detected Ballerina SDK version to solve the aforementioned issue.
Also related to the https://github.com/ballerina-platform/plugin-vscode/issues/194, we can improve this to support switching between locally pulled dist lists.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if …

Add status bar item to show current Ballerina SDK version

---

package.json
src/project/activator.ts
src/project/cli-cmds/add.ts
src/project/cli-cmds/cmd-runner.ts
src/telemetry/components.ts
src/telemetry/events.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/187

Introduce add module command

---

package.json
src/core/extension.ts
src/server/server.ts
test/language-server/lang-client.test.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/204

Update plugin configuration

---

package.json

Add config defaults for suggestions within snippets

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-alpha2-SNAPHOT to 2.0.0-alpha2.

Update version to 2.0.0-alpha2

---

src/core/extension.ts

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Show SDK error in status-bar item on plugin failures

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version from 2.0.0-alpha2 to 2.0.0-alpha3-SNAPSHOT.

Update version to 2.0.0-alpha3-SNAPSHOT

---

package.json

Fix https://github.com/ballerina-platform/plugin-vscode/issues/221

Update plugin settings

---

package.json

> Add configuration to enable/disable file watcher for project
Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/28650
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …

Add configuration to enable/disable file watcher for project

---

test/debugger/debugger.test.ts

Increase debug adapter test timeouts to fix test failures with git actions.

Increase debug adapter test timeout

---

test/debugger/debugger.test.ts

Increase debug adapter test timeouts to avoid test failures in git actions.

Increase debug adapter test timeouts

---

test/debugger/debugger.test.ts

Increase stepIn debug adapter test timeout to avoid git action failure.

Increase stepIn test timeout

---

src/project/cli-cmds/cmd-runner.ts

Execute commands in the integrated terminal instead of adding logs to the output channel.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/149

Execute commands in the integrated terminal

---

.github/workflows/publish-codecov1.yml
.github/workflows/publish-codecov2.yml

Update grammar submodule with latest changes.

Update grammar submodule

---

src/api-editor/activator.ts
src/bbe/activator.ts
src/core/extension.ts
src/core/preferences.ts
src/debugger/config-provider.ts
src/diagram/activator.ts
src/project/cli-cmds/add.ts
src/project/cli-cmds/build.ts
src/project/cli-cmds/cloud.ts
src/project/cli-cmds/doc.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts
src/telemetry/index.ts
src/trace-logs/activator.ts

Update plugin telemetry to honor `ballerina.enableTelemetry` setting.

Update telemetry to honor the setting

---

src/api-editor/activator.ts
src/core/extended-language-client.ts
src/core/messages.ts
src/extension.ts
src/project/activator.ts
src/utils/rpc/handler.ts

Add usability improvements, including https://github.com/ballerina-platform/plugin-vscode/issues/277 & https://github.com/ballerina-platform/plugin-vscode/issues/278.

Add usability improvements

---

README.md
composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version to 2.0.0-alpha3 for the release.

Update plugin version to 2.0.0-alpha3

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version to 2.0.0-beta1-SNAPSHOT

---

composer/packages/low-code-editor/src/Diagram.tsx
src/core/extension.ts
src/diagram/activator.ts
src/extension.ts
src/tree-view/activator.ts

Remove editor render for package, module, and service tree nodes.

Restrict editor render

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version to 2.0.0-alpha4-SNAPSHOT, & fix https://github.com/ballerina-platform/plugin-vscode/issues/333

Update version to alpha4-SNAPSHOT

---

.github/workflows/run-tests-windows.yml
build.gradle
gradle/jsProject.gradle
test/test-util.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/256
Test failures will be addressed with https://github.com/ballerina-platform/plugin-vscode/issues/338

Enable Windows tests

---

test/debugger/debugger.test.ts
test/language-server/lang-client.test.ts
test/test-util.ts

Related issue https://github.com/ballerina-platform/plugin-vscode/issues/338

Enable LS tests on Windows

---

src/core/extension.ts

Fix check for configured home

---

src/core/extension.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/344

Add debug logs to identify plugin failures

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version from 2.0.0-alpha4-SNAPSHOT to 2.0.0-alpah4.

Update plugin version to 2.0.0-alpha4

---

composer/packages/bbe/src/ExampleList.tsx

Fix https://github.com/ballerina-platform/plugin-vscode/issues/313

Fix sample listing when no search results found

---

.github/workflows/draft-release.yml

Temporary disable tests for release due to timeout issues.

Temporary disable tests for release

---

src/core/extended-language-client.ts
src/core/extension.ts
src/editor-support/activator.ts
src/editor-support/index.ts
src/editor-support/split-provider.ts
src/extension.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/215
Related LS fix: https://github.com/ballerina-platform/ballerina-lang/pull/29808

Introduce string split on editor

---

.github/workflows/draft-release.yml

Reverts ballerina-platform/plugin-vscode#354

Revert "Temporary disable tests for release"

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version from 2.0.0-alpha4 to 2.0.0-alpha5-SNAPSHOT.

Update version to 2.0.0-alpha5-SNAPSHOT

---

src/project/cli-cmds/cloud.ts

Fixes incorrect default values of cloud.deployment according to the specification.
Resolves ballerina-platform/module-ballerina-c2c#144
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …

Fix incorrect cloud default values

---

package.json
src/core/extension.ts
src/core/messages.ts
src/debugger/config-provider.ts
src/debugger/model.ts

The new set of debugging configurations looks like below.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/341

Update debugger configurations

---

src/core/extension.ts
src/editor-support/split-provider.ts
src/telemetry/components.ts
src/telemetry/events.ts
test/language-server/lang-client.test.ts

Update tests for alpha4 distribution, and fix https://github.com/ballerina-platform/plugin-vscode/issues/366

Update tests for alpha4 dist

---

src/bbe/activator.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/364

Fix example loading issues

---

package.json
src/core/extension.ts

Added the following plugin improvements
- Changed embedded toml supported extension to `be5invis.toml`.
- Reduced unwanted warn logs.

Plugin improvements

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update plugin version to 2.0.0-alpha5.

Update plugin version

---

.github/workflows/draft-release-without-test.yml

Add a git action to draft a release skipping the test run.

Add git action to draft a  release without tests

---

composer/lerna.json
composer/package-lock.json
composer/package.json
composer/packages/ast-model/package-lock.json
composer/packages/ast-model/package.json
composer/packages/bbe/package-lock.json
composer/packages/bbe/package.json
composer/packages/distribution/package.json
composer/packages/documentation/package-lock.json
composer/packages/documentation/package.json
composer/packages/font/package-lock.json
composer/packages/font/package.json
composer/packages/lang-service/package-lock.json
composer/packages/lang-service/package.json
composer/packages/theme/package-lock.json
composer/packages/theme/package.json
composer/tools/composer-cli/package-lock.json
composer/tools/composer-cli/package.json
gradle.properties
package-lock.json
package.json

Update version from 2.0.0-alpha5 to 2.0.0-beta-rc1-SNAPSHOT.

Update version to 2.0.0-beta-rc1-SNAPSHOT

---

package.json
src/core/extended-language-client.ts
src/core/extension.ts
src/core/preferences.ts
src/debugger/config-provider.ts
src/editor-support/activator.ts
src/editor-support/codelens-provider.ts
src/editor-support/split-provider.ts
src/project/activator.ts
src/project/cli-cmds/add.ts
src/project/cli-cmds/build.ts
src/project/cli-cmds/cloud.ts
src/project/cli-cmds/cmd-runner.ts
src/project/cli-cmds/doc.ts
src/project/cli-cmds/run.ts
src/project/cli-cmds/test.ts
src/telemetry/components.ts
src/telemetry/events.ts

Fix https://github.com/ballerina-platform/plugin-vscode/issues/150
Fix https://github.com/ballerina-platform/plugin-vscode/issues/18
Related LS PR: https://github.com/ballerina-platform/ballerina-lang/pull/30125

Introduce Run/Debug executor CodeLenses

---

src/tree-view/tree-data-provider.ts

Update package overview implementation to reload the overview depending on the active editor,
and enable the overview for single file projects.
Fix https://github.com/ballerina-platform/plugin-vscode/issues/380
Fix https://github.com/ballerina-platform/plugin-vscode/issues/379

Update package overview according to current editor

---

README.md

Update the link to VS Code Docs.
Fixes #286 
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no …

Update the Link to VS Code Docs
